create schema campaign_finances_test;

create table campaign_finances_test.indiv_contrib(
    CMTE_ID VARCHAR (20),
    AMNDT_IND VARCHAR (20),
    RPT_TP VARCHAR (20),
    TRANSACTION_PGI VARCHAR (20),
    IMAGE_NUM VARCHAR (20),
    TRANSACTION_TP VARCHAR (20),
    ENTITY_TP VARCHAR (20),
    NAME VARCHAR (20),
    CITY VARCHAR (20),
    STATE VARCHAR (20),
    ZIP_CODE VARCHAR (20),
    EMPLOYER VARCHAR (20),
    OCCUPATION VARCHAR (20),
    TRANSACTION_DT VARCHAR (20),
    TRANSACTION_AMT DECIMAL(12,2),
    OTHER_ID VARCHAR (20),
    TRAN_ID VARCHAR (20),
    FILE_NUM VARCHAR (20),
    MEMO_CD VARCHAR (20),
    MEMO_TEXT VARCHAR (20),
    SUB_ID VARCHAR (20)
   );

CREATE INDEX cmte_index ON indiv_contrib ("CMTE_ID");